Add VSB Finalizers and catch VSB errors
migtools/volume-snapshot-mover pull request #180
Opened 2023-01-10 16:50 UTC by dymurray

2023-01-10 16:57 UTC, dymurray commented on controllers/cleanup.go
> +		vsb.DeletionTimestamp == nil {
I should change this to `vsb.DeletionTimestamp.IsZero()`

2023-01-10 16:57 UTC, dymurray commented on controllers/cleanup.go
> +	if vsb.DeletionTimestamp == nil {
Change to use `IsZero()`

2023-01-11 15:39 UTC, eemcmullan commented on controllers/volumesnapshotbackup_controller.go
> +		r.Log.Info("Clean up successful")
should we keep this log in? Debug log?

2023-01-17 21:25 UTC, shubham-pampattiwar commented on api/v1alpha1/volumesnapshotbackup_types.go
> +// +kubebuilder:printcolumn:name="PVC Name",type=string,JSONPath=".status.sourcePVCData.name"
I believe the printer columns will show empty data

2023-02-13 21:12 UTC, kaovilai requested changes

2023-02-13 21:12 UTC, kaovilai commented on config/crd/bases/datamover.oadp.openshift.io_volumesnapshotbackups.yaml
> +      name: Age
Why is use `Age` which is different from `creationTimestamp`?

If it is truly a type of date.. it won't be displaying age (number of days/months/years) but rather a date (date/month/year) that VSB was created on.

2023-03-06 17:18 UTC, eemcmullan approved these changes

2023-03-06 17:28 UTC, dymurray commented
LGTM

2023-03-06 17:33 UTC, shubham-pampattiwar approved these changes

2023-03-06 17:42 UTC, kaovilai approved these changes

2023-03-06 17:47 UTC, merged