OADP-1663: securityContext per container
migtools/volume-snapshot-mover pull request #206
Opened 2023-04-21 19:07 UTC by eemcmullan

2023-04-23 12:26 UTC, kaovilai requested changes

2023-04-23 12:26 UTC, kaovilai commented on controllers/common.go
> +func buildPodSecurityContext(sc *corev1.SecurityContext, pod *corev1.Pod) *corev1.PodSecurityContext {
```suggestion
func buildMoverPodSecurityContext(sc corev1.SecurityContext, podSC corev1.PodSecurityContex) *corev1.PodSecurityContext {
```
Makes parameter not a pointer so parameter is a copy.
Pass in just security contexts as opposed to the entire pod definition

2023-04-24 22:10 UTC, kaovilai approved these changes

2023-04-24 22:17 UTC, shubham-pampattiwar approved these changes

2023-04-24 22:17 UTC, merged

2023-04-24 22:18 UTC, shubham-pampattiwar commented
/cherry-pick `oadp-1.2`

2023-04-24 22:19 UTC, shubham-pampattiwar commented
/cherry-pick oadp-1.2